spring:
  application:
    name: demo
  profiles:
    include: api-key  # application-api-key.yml 가져옴
    
  datasource:
    # IPv4 환경에서는 반드시 pooler 주소와 6543 포트를 써야 함
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.odlfedzyieuplylcggzb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성 (개발 초기용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: "bm9ib2R5LWtub3dzLXRoaXMtaXMtYS1zZWNyZXQta2V5LWZvci1qd3Q=" # Base64 인코딩된 시크릿키 (운영환경에서는 환경변수로 교체)
  access-token-expiration: 900000      # 15분 (ms) - API 호출 시 사용
  refresh-token-expiration: 604800000  # 7일 (ms) - accessToken 만료 시 재발급용
